### ISSUE TITLE
Unnecessary items in sidebar

### ISSUE THREAD

**Issue by inventor02** [RatelimitedME/RLPanel#3]
Template items have been left in the sidebar, such as "Advanced Plugins" and "Charts". These should be commented out.

![Image](https://totally-not.a-sketchy.site/3f862f.png)

**Comment by gtsatsis** [comment]
These were left in for debugging purposes (And ease of use on my end) -- Will be removed in my next update to the panel

**Comment by gtsatsis** [comment]
I can confirm that these buttons have been removed in my local copy and are going to be pushed along with the web upload function once it is done (As well as making the sidebar, footer, etc. on their own files and loading them up from there. Mainly for convinience sake)

**Comment by gtsatsis** [comment]
After taking a long vacation from programming, I can confirm that these fixes have been deployed.

Issue closed.
